# Generated by Django 5.2 on 2025-07-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstartor',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('mobile', models.TextField()),
                ('role', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('university', models.TextField()),
                ('branch', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('code', models.TextField(unique=True)),
                ('principal', models.TextField()),
                ('mobile', models.TextField()),
                ('role', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('pincode', models.TextField()),
                ('affiliation', models.TextField()),
                ('website', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.TextField()),
                ('payment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('year', models.TextField()),
                ('semester', models.TextField()),
                ('name', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.college')),
            ],
            options={
                'unique_together': {('college', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='college',
            name='branches',
            field=models.ManyToManyField(through='app.CollegeBranch', to='app.branch'),
        ),
        migrations.CreateModel(
            name='SubjectBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.branch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
            options={
                'unique_together': {('subject', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='branches',
            field=models.ManyToManyField(through='app.SubjectBranch', to='app.branch'),
        ),
    ]
