# Generated by Django 5.2 on 2025-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstartor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('principal', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('branches', models.ManyToManyField(to='app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('branches', models.ManyToManyField(to='app.branch')),
            ],
        ),
    ]
